### ISSUE TITLE
Android 5.1.1

### ISSUE THREAD

**Issue by WHuaJian** [crossbario/autobahn-java#232]
On Android 5.1.1 systems, WebSocketConnection sometimes reports java.lang.NullPointerException

**Comment by om26er** [comment]
Which version of the library are you using ? Can you provide app' logcat ?

**Comment by WHuaJian** [comment]
I'm using the last version of the library，The logs are as follows：
   java.lang.NullPointerException: Attempt to invoke virtual method 'void de.tavendo.autobahn.i.a(java.lang.Object)' on a null object reference
	at de.tavendo.autobahn.d.a(WebSocketConnection.java:137)
	at cn.k12cloud.k12cloud2cv3.service.WebSocketService$4.a(WebSocketService.java:176)
	at de.tavendo.autobahn.d$1.handleMessage(WebSocketConnection.java:370)
	at android.os.Handler.dispatchMessage(Handler.java:105)
	at android.os.Looper.loop(Looper.java:156)
	at android.app.ActivityThread.main(ActivityThread.java:6577)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:941)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:831)

The code for error in my APP is：
  
    if (webSocketConnection != null)
         webSocketConnection.sendTextMessage(getLoginStr());

webSocketConnection is NullPointerException,Cause program crash。

**Comment by om26er** [comment]
The version that you are using is no longer supported. We are currently working a rewrite which will have WAMPv2 support.
