### ISSUE TITLE
IllegalStateException during reconnection

### ISSUE THREAD

**Issue by 0xAliHn** [crossbario/autobahn-java#304]
When first time connecting no issue after reconnection getting this exception: 
```
java.lang.IllegalStateException: Connection must be set only once.
                                                                                         at de.tavendo.autobahn.WebSocketConnectionHandler.setConnection(WebSocketConnectionHandler.java:85)
                                                                                         at de.tavendo.autobahn.WebSocketConnection$4.handleMessage(WebSocketConnection.java:606)
                                                                                         at android.os.Handler.dispatchMessage(Handler.java:102)
                                                                                         at android.os.Looper.loop(Looper.java:154)
                                                                                         at android.app.ActivityThread.main(ActivityThread.java:6692)
                                                                                         at java.lang.reflect.Method.invoke(Native Method)
                                                                                         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
                                                                                         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```

**Comment by om26er** [comment]
where did you download that library ? Seems you are using a deprecated(and very old) version.

**Comment by 0xAliHn** [comment]
@om26er This is not old version. I just download it today and replace my old library with updated one then getting this issue once re-connection happen.

**Comment by om26er** [comment]
> @om26er This is not old version. I just download it today and replace my old library with updated one then getting this issue once re-connection happen.

Can you tell the location from where you downloaded the library ? The package name `de.tavendo.autobahn` is legacy and we have since started being `io.crossbar.autobahn`. The latest version is called autobahn-android. https://search.maven.org/#search%7Cga%7C1%7Ca%3A%22autobahn-android%22

Also we have a known issue in the latest release as well https://github.com/crossbario/autobahn-java/issues/280

**Comment by 0xAliHn** [comment]
@om26er  I have downloaded from this branch: [link](https://github.com/crossbario/autobahn-java/tree/master/autobahn)

After downloading replaced all of my existing files with updated files. Basically I didn't change my existing package name that's why its showing `de.tavendo.autobahn`
So, When can we get a fix for this issue?

**Comment by om26er** [comment]
> @om26er I have downloaded from this branch: link

Could you please consider adding this line in your build.gradle ?
`compile 'io.crossbar.autobahn:autobahn-android:17.10.3'` 

> After downloading replaced all of my existing files with updated files. Basically I didn't change my existing package name that's why its showing de.tavendo.autobahn

That actually confuses me, so you copy-pasted all the files from current master into your project but kept the old package name ? Why not just add the gradle project ?

I should have a fix for https://github.com/crossbario/autobahn-java/issues/280 tonight (hopefully).

**Comment by om26er** [comment]
https://github.com/crossbario/autobahn-java/pull/305 fixes both this and https://github.com/crossbario/autobahn-java/issues/280

**Comment by om26er** [comment]
fixed by https://github.com/crossbario/autobahn-java/pull/305
