### ISSUE TITLE
TooLongFrameException: Response entity too large

### ISSUE THREAD

**Issue by bspeice** [crossbario/autobahn-java#340]
When running what I would've expected is a fairly simple client, I'm getting an exception when connecting to crossbar. Crossbar itself is running in a Pypy container, and I'm trying to connect using the following code:

```kotlin
val executor = Executors.newSingleThreadExecutor()
val session = Session(executor)
val client = Client(session, wsUrl, realm, executor)

val latch = CountDownLatch(2)
session.addOnConnectListener({ s: Session -> latch.countDown() })
session.addOnDisconnectListener({ s: Session, clean: Boolean -> latch.countDown() })

val exitInfo = client.connect()
try {
    exitInfo.get(3, TimeUnit.SECONDS)
    latch.await(3, TimeUnit.SECONDS)
} catch (e: Exception) {
    println("Error during processing: ")
    e.printStackTrace()
}
```

The exception I'm getting is:
```
io.netty.handler.codec.TooLongFrameException: Response entity too large: HttpObjectAggregator$AggregatedFullHttpResponse(decodeResult: success, version: HTTP/1.1, content: CompositeByteBuf(ridx: 0, widx: 8051, cap: 8051, components=8))
HTTP/1.1 200 OK
Server: Crossbar/17.11.1
Date: Mon, 13 Nov 2017 05:18:43 GMT
Content-Type: text/html
        at io.netty.handler.codec.http.HttpObjectAggregator.handleOversizedMessage(HttpObjectAggregator.java:213)
        at io.netty.handler.codec.http.HttpObjectAggregator.handleOversizedMessage(HttpObjectAggregator.java:53)
        at io.netty.handler.codec.MessageAggregator.invokeHandleOversizedMessage(MessageAggregator.java:388)
        at io.netty.handler.codec.MessageAggregator.decode(MessageAggregator.java:282)
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:88)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:332)
        at io.netty.channel.CombinedChannelDuplexHandler$DelegatingChannelHandlerContext.fireChannelRead(CombinedChannelDuplexHandler.java:435)
        at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:293)
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:267)
        at io.netty.channel.CombinedChannelDuplexHandler.channelRead(CombinedChannelDuplexHandler.java:250)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:332)
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1319)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:354)
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:340)
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:904)
        at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:123)
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:571)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:512)
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:426)
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:398)
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:805)
        at io.netty.util.concurrent.DefaultThreadFactory$DefaultRunnableDecorator.run(DefaultThreadFactory.java:145)
        at java.lang.Thread.run(Thread.java:748)
Nov 13, 2017 12:18:43 AM io.crossbar.autobahn.wamp.transports.NettyWebSocketClientHandler
```

Should I be doing something different? Is there a way I should be trying to avoid this?

**Comment by oberstet** [comment]
Are you sure you are connecting to the WAMP/WebSocket endpoint of Crossbar.io?

Because in the response above you can see `Content-Type: text/html`

That means, Crossbar.io has actually rendered a status page, not opened a new WebSocket connection.

Eg with default Crossbar.io node configuraton, don't forget the trailing `ws` : `ws://localhost:8080/ws`

**Comment by bspeice** [comment]
Ah, the trailing ws wasn't there in the URL, thank you. Feel free to close
this.
