### ISSUE TITLE
Allow to "switch off" client initiated pings on an active session

### ISSUE THREAD

**Issue by om26er** [crossbario/autobahn-java#397]
To allow for flexibility we need to expose the option to completely turn off auto pings.

**Comment by oberstet** [comment]
so setting a timeout of `0` (not `null`) in `options` when setting would completely deactivate the `mPingerTask`? so a follow up to https://github.com/crossbario/autobahn-java/pull/394? as I was wondering as you just added the latter;)

**Comment by om26er** [comment]
> so setting a timeout of 0 (not null) in options when setting would completely deactivate the mPingerTask? so a follow up to #394? as I was wondering as you just added the latter;)

yes, that's true. Currently providing `0` as ping timeout results in a IllegalArgumentException
```
04-25 13:02:26.179 22351-22351/io.crossbar.autobahn.demogallery E/AndroidRuntime: FATAL EXCEPTION: main
    Process: io.crossbar.autobahn.demogallery, PID: 22351
    java.lang.IllegalArgumentException
        at java.util.concurrent.ScheduledThreadPoolExecutor.scheduleAtFixedRate(ScheduledThreadPoolExecutor.java:566)
        at java.util.concurrent.Executors$DelegatedScheduledExecutorService.scheduleAtFixedRate(Executors.java:658)
        at io.crossbar.autobahn.websocket.WebSocketConnection$2.handleMessage(WebSocketConnection.java:639)
        at android.os.Handler.dispatchMessage(Handler.java:102)
        at android.os.Looper.loop(Looper.java:154)
        at android.app.ActivityThread.main(ActivityThread.java:6692)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1468)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1358)
```
