### ISSUE TITLE
AndroidRuntime: FATAL EXCEPTION: main

### ISSUE THREAD

**Issue by ejChathuranga** [crossbario/autobahn-java#422]
To download via Gradle we can use
```
dependencies {
    implementation 'io.crossbar.autobahn:autobahn-android:18.5.1'
}
```
But after synced and run over the real device( Mi A1, OS 8.0.0 ) before starting the app, means when app lunching occurs error. The logcat will shows below. Is there any special configurations for add autobahn java into my project??

`08-17 10:50:55.522 16010-16010/com.venusit.ej.autobahntest E/AndroidRuntime: FATAL EXCEPTION: main
    Process: com.venusit.ej.autobahntest, PID: 16010
    java.lang.RuntimeException: Unable to instantiate activity ComponentInfo{com.venusit.ej.autobahntest/com.venusit.ej.autobahntest.MainActivity}: java.lang.ClassNotFoundException: Didn't find class "com.venusit.ej.autobahntest.MainActivity" on path: DexPathList[[zip file "/data/app/com.venusit.ej.autobahntest-AKZ_UdGUYjPv28REugEU4A==/base.apk"],nativeLibraryDirectories=[/data/app/com.venusit.ej.autobahntest-AKZ_UdGUYjPv28REugEU4A==/lib/arm64, /data/app/com.venusit.ej.autobahntest-AKZ_UdGUYjPv28REugEU4A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2732)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2906)
        at android.app.ActivityThread.-wrap11(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605)
        at android.os.Handler.dispatchMessage(Handler.java:105)
        at android.os.Looper.loop(Looper.java:172)
        at android.app.ActivityThread.main(ActivityThread.java:6637)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
     Caused by: java.lang.ClassNotFoundException: Didn't find class "com.venusit.ej.autobahntest.MainActivity" on path: DexPathList[[zip file "/data/app/com.venusit.ej.autobahntest-AKZ_UdGUYjPv28REugEU4A==/base.apk"],nativeLibraryDirectories=[/data/app/com.venusit.ej.autobahntest-AKZ_UdGUYjPv28REugEU4A==/lib/arm64, /data/app/com.venusit.ej.autobahntest-AKZ_UdGUYjPv28REugEU4A==/base.apk!/lib/arm64-v8a, /system/lib64, /system/vendor/lib64]]
        at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:93)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:379)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
        at android.app.Instrumentation.newActivity(Instrumentation.java:1174)
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2722)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2906) 
        at android.app.ActivityThread.-wrap11(Unknown Source:0) 
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1605) 
        at android.os.Handler.dispatchMessage(Handler.java:105) 
        at android.os.Looper.loop(Looper.java:172) 
        at android.app.ActivityThread.main(ActivityThread.java:6637) 
        at java.lang.reflect.Method.invoke(Native Method) 
        at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
    	Suppressed: java.io.IOException: Failed to open dex files from /data/app/com.venusit.ej.autobahntest-AKZ_UdGUYjPv28REugEU4A==/base.apk because: Failure to verify dex file '/data/app/com.venusit.ej.autobahntest-AKZ_UdGUYjPv28REugEU4A==/base.apk': Bad method handle type 7
        at dalvik.system.DexFile.openDexFileNative(Native Method)
        at dalvik.system.DexFile.openDexFile(DexFile.java:353)
        at dalvik.system.DexFile.<init>(DexFile.java:100)
        at dalvik.system.DexFile.<init>(DexFile.java:74)
        at dalvik.system.DexPathList.loadDexFile(DexPathList.java:374)
        at dalvik.system.DexPathList.makeDexElements(DexPathList.java:337)
        at dalvik.system.DexPathList.<init>(DexPathList.java:157)
        at dalvik.system.BaseDexClassLoader.<init>(BaseDexClassLoader.java:65)
        at dalvik.system.PathClassLoader.<init>(PathClassLoader.java:64)
        at com.android.internal.os.PathClassLoaderFactory.createClassLoader(PathClassLoaderFactory.java:43)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:69)
        at android.app.ApplicationLoaders.getClassLoader(ApplicationLoaders.java:36)
        at android.app.LoadedApk.createOrUpdateClassLoaderLocked(LoadedApk.java:669)
        at android.app.LoadedApk.getClassLoader(LoadedApk.java:702)
        at android.app.LoadedApk.getResources(LoadedApk.java:929)
        at android.app.ContextImpl.createAppContext(ContextImpl.java:2242)
        at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5708)
        at android.app.ActivityThread.-wrap1(Unknown Source:0)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1673)`

**Comment by om26er** [comment]
@ejChathuranga The issue is not with autobahn-java, rather its your app that's having the issues. Please clean the project and rebuild and it should be good.

The current error is that app does not find your MainActivity.
